### ISSUE TITLE
can we have an option to show only when `debug.toolBarLocation` is false ?

### ISSUE THREAD

**Issue by ctf0** [EverlastEngineering/debugInTitlebar#6]
i know its kinda of a picky option, but why not ? it will be more of an add-on to the original feature of the editor.

**Comment by DominicVonk** [comment]
Sure it's easy to add let me make a pr

**Comment by DominicVonk** [comment]
[Pull Request](https://github.com/EverlastEngineering/debugInTitlebar/pull/7)

**Comment by EverlastEngineering** [comment]
PR merged. I added you @DominicVonk! Hope you had a good holiday!

**Comment by EverlastEngineering** [comment]
I'm going to revert this. It's created an 'interdependent UX' which is a general bad design in UX when options are in the same place. What this means is because the option to change the built-in toolbar from hidden, floating or dock, the setting for the titlebar debug is _also_ in that area, so a user would normally expect them to not be interdependent on each other.

I did a quick run with another option to "show only when the built in toolbar is hidden" option but... spaghetti code much? It wasn't any more useful than just changing it in two places.

**Comment by EverlastEngineering** [comment]
Moreso, if someone has their debug set to floating (the default) then this plugin will not show for them at all until they discover it has to be set to hidden (hence the setting I was going to do, but its just a mess of bools).

Hope you understand.

**Comment by ctf0** [comment]
np, i originally was after a new config that would allow that, so user would have exactly what he expected instead of figuring out.

still thanks for all ur work. 👍

**Comment by DominicVonk** [comment]
I will change some settings within the extension so it will automatically change it to the docked option because I think its the best option.

**Comment by EverlastEngineering** [comment]
Is there a way to prompt the user for a setting upon install? I’m hesitant
to automagically change (somewhat) unrelated settings but prompting them
would be ideal.
